/*postgres code*/
CREATE TABLE CUSTOMER (
    ID INT,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    ADDRESS VARCHAR,
    AGE FLOAT,
    PRIMARY KEY (ID)

INSERT INTO CUSTOMER VALUES 
(1,'ADAM','SMITH', '9 AND QUARTERS, HEMMING LANE',45),
(2,'SAD','SMITH', '9 AND HALF, HEMMING LANE',47),
(3,'ADAM','SANDLER', '9, HEMMING LANE',48);

INSERT INTO CUSTOMER VALUES 
(1,'ADAM','SMITH', 'New address',45);

INSERT INTO CUSTOMER VALUES
(1,'ADAM','SMITH', 'New address',45)
ON CONFLICT (ID)
DO
    UPDATE SET ADDRESS=EXCLUDED.ADDRESS

/* Mysql code */
create database dwh;

CREATE TABLE dwh.CUSTOMER (
    ID INT,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    ADDRESS VARCHAR(100),
    AGE FLOAT,
    PRIMARY KEY (ID))

INSERT INTO dwh.CUSTOMER VALUES 
(1,'ADAM','SMITH', '9 AND QUARTERS, HEMMING LANE',45),
(2,'SAD','SMITH', '9 AND HALF, HEMMING LANE',47),
(3,'ADAM','SANDLER', '9, HEMMING LANE',48);


INSERT INTO dwh.CUSTOMER VALUES
(1,'ADAM','SMITH', 'NEW ADDRESS',45)
ON DUPLICATE KEY UPDATE ADDRESS = 'NEW ADDRESS';